version: "3.2"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "SuperStrongPassword!" 
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Standard"
    volumes:
      - data-mssql2022:/var/opt/mssql
volumes:
  data-mssql2022:

   
